Name : Rashmi Mahajan 
Batch : Data science Masters 
Topic : Numpy
Date : 26/2/2023

Consider the below code to answer further questions:


import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
to print the data types of both the variables.



Variable list_   is of list data type
whereas array_list   is   numpy.ndarray type

In [1]:
list_ = [ '1','2','3','4','5']
print(list_)
# This the a normal list that we use in python
# It's data types is <class 'list'>
# No new library is required for this
print(type(list_))

['1', '2', '3', '4', '5']
<class 'list'>


In [2]:
import numpy as np
array_list = np.array(object = list_)
print(array_list)
# This is an numpy array
# It's data types is <class 'numpy.ndarray'>
# We need to import numpy to use this
print(type(array_list))

['1' '2' '3' '4' '5']
<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and 
arra_list.

In [3]:
# type of list_ 
print(type(list_))
# type of array_list
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [4]:
# type of each element in list_
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [5]:
# Array_list
array_list.dtype

dtype('<U1')

In [6]:
# type of each element in array_list
for i in array_list :
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and 
arra_list? If so then print the data types of each and every element present in both the variables, list_ 
and arra_list.

Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)


In [7]:
array_list = np.array(object = list_, dtype = int)
array_list 

array([1, 2, 3, 4, 5])

In [8]:
type(array_list)

numpy.ndarray

In [9]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
print(num_list)
num_array = np.array(object = num_list)
print(num_array)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


In [10]:
type(num_list)

list

In [11]:
type(num_array)

numpy.ndarray

Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size




In [12]:
# (i) shape
num_array.shape

(2, 3)

In [13]:
# (ii) size
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]




In [14]:
import numpy as np
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.matrix(np.zeros((3,3)))

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [16]:
import numpy as np
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.matrix(np.eye(5))

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])